version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
env:
  variables:
    "testEnv" : "defaultTestVariable"
  exportedVariables:
    - VERS
    - param1

steps:
  - type: Command
    name: "pre-build"
    command: |
      git clone https://github.com/dockersamples/k8s-wordsmith-demo.git
  - type: Command
    name: "build"
    command: |
      docker compose up --build
  - type: Command
    name: "post-build"
    command: |
      echo "docker build completed"
